# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teste01.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rteste01.proto\x12\x05teste\",\n\nSoxRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08greeting\x18\x02 \x01(\t\"\x1b\n\x08SoxReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"F\n\x0fSoxDelayedReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\"\n\x07request\x18\x02 \x03(\x0b\x32\x11.teste.SoxRequest2\xed\x01\n\x0eGiornoGiovanna\x12-\n\x07SayYume\x12\x11.teste.SoxRequest\x1a\x0f.teste.SoxReply\x12-\n\x05\x43ombo\x12\x11.teste.SoxRequest\x1a\x0f.teste.SoxReply0\x01\x12:\n\x0bKingCrimson\x12\x11.teste.SoxRequest\x1a\x16.teste.SoxDelayedReply(\x01\x12\x41\n\x17GoldenExperienceRequiem\x12\x11.teste.SoxRequest\x1a\x0f.teste.SoxReply(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'teste01_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SOXREQUEST']._serialized_start=24
  _globals['_SOXREQUEST']._serialized_end=68
  _globals['_SOXREPLY']._serialized_start=70
  _globals['_SOXREPLY']._serialized_end=97
  _globals['_SOXDELAYEDREPLY']._serialized_start=99
  _globals['_SOXDELAYEDREPLY']._serialized_end=169
  _globals['_GIORNOGIOVANNA']._serialized_start=172
  _globals['_GIORNOGIOVANNA']._serialized_end=409
# @@protoc_insertion_point(module_scope)
