# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teste02.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rteste02.proto\x12\x07teste02\"2\n\x04Tree\x12\x11\n\tclient_ID\x18\x01 \x01(\x05\x12\x17\n\x0fserialised_tree\x18\x02 \x01(\x0c\x32\x36\n\x04Rias\x12.\n\x0creceive_tree\x12\r.teste02.Tree\x1a\r.teste02.Tree0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'teste02_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TREE']._serialized_start=26
  _globals['_TREE']._serialized_end=76
  _globals['_RIAS']._serialized_start=78
  _globals['_RIAS']._serialized_end=132
# @@protoc_insertion_point(module_scope)
