# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import teste02_pb2 as teste02__pb2


class RiasStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.receive_tree = channel.unary_stream(
                '/teste02.Rias/receive_tree',
                request_serializer=teste02__pb2.Tree.SerializeToString,
                response_deserializer=teste02__pb2.Tree.FromString,
                )


class RiasServicer(object):
    """Missing associated documentation comment in .proto file."""

    def receive_tree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RiasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'receive_tree': grpc.unary_stream_rpc_method_handler(
                    servicer.receive_tree,
                    request_deserializer=teste02__pb2.Tree.FromString,
                    response_serializer=teste02__pb2.Tree.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'teste02.Rias', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Rias(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def receive_tree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/teste02.Rias/receive_tree',
            teste02__pb2.Tree.SerializeToString,
            teste02__pb2.Tree.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
