# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multclient.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10multclient.proto\x12\nmultclient\"9\n\x0bTree_CLient\x12\x11\n\tclient_ID\x18\x01 \x01(\x05\x12\x17\n\x0fserialised_tree\x18\x02 \x01(\x0c\"&\n\x0bTree_Server\x12\x17\n\x0fserialised_tree\x18\x01 \x01(\x0c\x32X\n\x0fTokisaki_Kurumi\x12\x45\n\x0f\x61ggregate_trees\x12\x17.multclient.Tree_CLient\x1a\x17.multclient.Tree_Server0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multclient_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TREE_CLIENT']._serialized_start=32
  _globals['_TREE_CLIENT']._serialized_end=89
  _globals['_TREE_SERVER']._serialized_start=91
  _globals['_TREE_SERVER']._serialized_end=129
  _globals['_TOKISAKI_KURUMI']._serialized_start=131
  _globals['_TOKISAKI_KURUMI']._serialized_end=219
# @@protoc_insertion_point(module_scope)
