# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import multclient_pb2 as multclient__pb2


class Tokisaki_KurumiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.aggregate_trees = channel.unary_stream(
                '/multclient.Tokisaki_Kurumi/aggregate_trees',
                request_serializer=multclient__pb2.Tree_CLient.SerializeToString,
                response_deserializer=multclient__pb2.Tree_Server.FromString,
                )


class Tokisaki_KurumiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def aggregate_trees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Tokisaki_KurumiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'aggregate_trees': grpc.unary_stream_rpc_method_handler(
                    servicer.aggregate_trees,
                    request_deserializer=multclient__pb2.Tree_CLient.FromString,
                    response_serializer=multclient__pb2.Tree_Server.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'multclient.Tokisaki_Kurumi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tokisaki_Kurumi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def aggregate_trees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/multclient.Tokisaki_Kurumi/aggregate_trees',
            multclient__pb2.Tree_CLient.SerializeToString,
            multclient__pb2.Tree_Server.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
